# Generated by Django 4.2.4 on 2023-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ltype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pdes', models.CharField(default=None, max_length=300)),
                ('price', models.CharField(default=None, max_length=50)),
                ('cap', models.CharField(default=None, max_length=50)),
                ('rdate', models.DateField(default=None)),
                ('sold', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
