# Generated by Django 4.2.4 on 2023-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=5)),
                ('review', models.CharField(max_length=250)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
            ],
        ),
    ]
