# Generated by Django 4.2.4 on 2023-11-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_feedback_is_active_alter_feedback_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='is_active',
            new_name='is_valid',
        ),
    ]
