# Generated by Django 4.2.4 on 2023-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_is_active_feedback_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('qauantity', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('pay_method', models.CharField(max_length=50)),
                ('reg_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
