# Generated by Django 4.2.4 on 2023-11-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_record_alter_feedback_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='qauantity',
            new_name='quantity',
        ),
    ]
