# Generated by Django 4.2.4 on 2023-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_qauantity_record_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('price', models.CharField(default=None, max_length=50)),
                ('quantity', models.CharField(default=None, max_length=50)),
                ('rdate', models.DateField(default=None)),
            ],
        ),
    ]
